name: nexo_logger
version: 0.1.0
description: Logger abstractions and Talker adapter for nexo.
repository: https://github.com/DoolotbekovSultan/nexo

environment:
  sdk: ^3.11.3
  flutter: ">=1.17.0"

dependencies:
  talker: ^5.1.16
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
