name: nexo
version: 0.1.0
repository: https://github.com/DoolotbekovSultan/nexo
documentation: https://github.com/DoolotbekovSultan/nexo/blob/main/doc/README.md
description: Modular toolkit for Flutter apps — UseCase layer, sealed Result, unified Failure model, BLoC/Cubit wrappers, networking, data sources, logging, and UI utilities.

environment:
  sdk: ^3.11.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  nexo_bloc: ^0.1.0
  nexo_core: ^0.1.0
  nexo_datasource: ^0.1.0
  nexo_errors: ^0.1.0
  nexo_errors_firebase: ^0.1.0
  nexo_logger: ^0.1.0
  nexo_network: ^0.1.0
  nexo_sync: ^0.1.0
  nexo_testing: ^0.1.0
  nexo_ui: ^0.1.0
  nexo_usecase: ^0.1.0
  nexo_validation: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  dio: ^5.10.0
  flutter_bloc: ^9.1.1

dependency_overrides:
  nexo_bloc:
    path: packages/nexo_bloc
  nexo_core:
    path: packages/nexo_core
  nexo_datasource:
    path: packages/nexo_datasource
  nexo_errors:
    path: packages/nexo_errors
  nexo_errors_drift:
    path: packages/nexo_errors_drift
  nexo_errors_firebase:
    path: packages/nexo_errors_firebase
  nexo_errors_hive:
    path: packages/nexo_errors_hive
  nexo_errors_isar:
    path: packages/nexo_errors_isar
  nexo_logger:
    path: packages/nexo_logger
  nexo_network:
    path: packages/nexo_network
  nexo_sync:
    path: packages/nexo_sync
  nexo_testing:
    path: packages/nexo_testing
  nexo_ui:
    path: packages/nexo_ui
  nexo_usecase:
    path: packages/nexo_usecase
  nexo_validation:
    path: packages/nexo_validation
