name: nexo_bloc
version: 0.1.0
description: BLoC/Cubit abstractions and helpers for nexo.
repository: https://github.com/DoolotbekovSultan/nexo

environment:
  sdk: ^3.11.3
  flutter: ">=1.17.0"

dependencies:
  nexo_core: ^0.1.0
  nexo_errors: ^0.1.0
  nexo_logger: ^0.1.0
  bloc: ^9.2.0
  bloc_concurrency: ^0.3.0
  flutter_bloc: ^9.1.1
  stream_transform: ^2.1.1
  flutter:
    sdk: flutter
