import 'init_plan.dart';

/// Template renderer for `nexo init` scaffold files.
///
/// Picks the right template based on file path and renders substitutions.
abstract final class InitTemplateRenderer {
  InitTemplateRenderer._();

  /// Renders Dart source for an init file.
  static String render(String relativePosixPath, InitOptions options) {
    final norm = relativePosixPath.replaceAll(r'\', '/');
    final template = _pickTemplate(norm, options);
    return _substitute(template, options);
  }

  static String _pickTemplate(String norm, InitOptions options) {
    if (norm.endsWith('lib/main.dart')) return _tplMain;
    if (norm.endsWith('lib/app.dart')) return _tplApp;
    if (norm.endsWith('lib/core/config.dart')) return _tplConfig;
    if (norm.endsWith('lib/core/di/di.dart')) return _tplDi;
    if (norm.endsWith('lib/core/di/modules/network_module.dart')) {
      return _tplNetworkModule;
    }
    if (norm.endsWith('lib/core/di/modules/storage_module.dart')) {
      return _tplStorageModule;
    }
    if (norm.endsWith('lib/core/di/modules/logger_module.dart')) {
      return _tplLoggerModule;
    }
    if (norm.endsWith('lib/core/network/auth_interceptor_bindings.dart')) {
      return _tplAuthBindings;
    }

    // Routing
    if (norm.endsWith('lib/app/router/app_router.dart')) {
      return options.hasAutoRoute ? _tplAutoRouteRouter : _tplGoRouter;
    }
    if (norm.endsWith('lib/app/navigation/auth_guard.dart')) {
      return _tplAuthGuard;
    }
    if (norm.endsWith('lib/app/navigation/guest_guard.dart')) {
      return _tplGuestGuard;
    }

    return _tplFallback;
  }

  static String _substitute(String template, InitOptions options) {
    final mockEnv = options.mockByDefault ? 'mock' : 'prod';
    final sentryImport = options.sentry
        ? "import 'package:sentry_flutter/sentry_flutter.dart';"
        : '';
    final sentryInit = options.sentry
        ? '''
    // Sentry: crash reporting / Sentry: отчётность об ошибках
    await SentryFlutter.init(
      (options) {
        options.dsn = const String.fromEnvironment('SENTRY_DSN');
      },
    );'''
        : '';
    final sentryDsn = options.sentry
        ? "const String kSentryDsn = String.fromEnvironment('SENTRY_DSN');"
        : '';

    return template
        .replaceAll('{{appName}}', options.appName)
        .replaceAll('{{mockEnv}}', mockEnv)
        .replaceAll('{{sentryImport}}', sentryImport)
        .replaceAll('{{sentryInit}}', sentryInit)
        .replaceAll('{{sentryDsn}}', sentryDsn);
  }
}


// Fallback


const _tplFallback = r'''
// Placeholder generated by nexo_cli init.
// Заглушка, сгенерированная nexo_cli init.
''';


// main.dart — Application entry point / Точка входа приложения


const _tplMain = r'''
import 'package:flutter/material.dart';
import 'package:get_it/get_it.dart';
import 'package:nexo/nexo.dart';

import 'app.dart';
import 'core/config.dart';
import 'core/di/di.dart';
{{sentryImport}}

/// App entry point / Точка входа приложения.
///
/// Wraps everything in [NexoFlutterErrors.runAppInZone] to catch all
/// unhandled errors and forward them to [NexoLogger] + [NexoCrashReporter].
///
/// Оборачивает всё в [NexoFlutterErrors.runAppInZone] для перехвата
/// всех необработанных ошибок и отправки в [NexoLogger] + [NexoCrashReporter].
Future<void> main() async {
  await NexoFlutterErrors.runAppInZone(() async {
    WidgetsFlutterBinding.ensureInitialized();

    // Resolve environment (mock / prod) from --dart-define flags.
    // Определяем окружение (mock / prod) из флагов --dart-define.
    final resolvedEnv = AppEnvironment.resolve(
      useMock: kUseMock,
    );
    debugPrint('[App] mode=$resolvedEnv, api=$kApiBaseUrl');

    // Initialize dependency injection (GetIt + Injectable).
    // Инициализация DI (GetIt + Injectable).
    await configureDependencies(environment: resolvedEnv);

    // Set up logger and crash reporter from DI.
    // Настройка логгера и краш-репортера из DI.
    final logger = GetIt.instance<NexoLogger>();
    final crashReporter = GetIt.instance<NexoCrashReporter>();

    // Install global Flutter error handler.
    // Установка глобального обработчика ошибок Flutter.
    NexoFlutterErrors.install(logger: logger, crashReporter: crashReporter);

    // Attach BlocObserver for logging state changes.
    // Подключение BlocObserver для логирования изменений состояний.
    Bloc.observer = NexoBlocObserver(logger, crashReporter: crashReporter);
{{sentryInit}}
    runApp(const {{appName}}App());
  });
}
''';


// app.dart — Root widget / Корневой виджет


const _tplApp = r'''
import 'package:flutter/material.dart';

/// Root widget of the application.
/// Корневой виджет приложения.
///
/// Replace [MaterialApp] with [MaterialApp.router] when you add routing.
/// Замените [MaterialApp] на [MaterialApp.router] при добавлении роутинга.
class {{appName}}App extends StatelessWidget {
  const {{appName}}App({super.key});

  @override
  Widget build(BuildContext context) {
    // MaterialApp — configures the app's visual theme, navigation, and locale.
    // MaterialApp — настраивает тему, навигацию и локализацию приложения.
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: '{{appName}}',
      theme: ThemeData(
        colorSchemeSeed: Colors.blue,
        useMaterial3: true,
      ),
      // TODO(nexo): replace with your router config when routing is added.
      // TODO(nexo): замените на конфигурацию роутера при добавлении роутинга.
      home: const Scaffold(
        body: Center(
          child: Text('Welcome to {{appName}}'),
        ),
      ),
    );
  }
}
''';


// config.dart — Environment & API config / Окружение и конфигурация API


const _tplConfig = r'''
import 'package:flutter/foundation.dart';

/// Application environments for dependency injection.
/// Окружения приложения для dependency injection.
///
/// Used by injectable to register environment-specific implementations.
/// Используется injectable для регистрации реализаций для конкретного окружения.
abstract final class AppEnvironment {
  static const mock = 'mock';
  static const prod = 'prod';

  static String resolve({required bool useMock}) =>
      useMock ? mock : prod;
}

/// Whether to use mock datasources (default: true in debug, false in release).
/// Использовать ли mock-датасорсы (по умолчанию: true в debug, false в release).
///
/// Override with: --dart-define=USE_MOCK=false
/// Переопределить: --dart-define=USE_MOCK=false
bool get kUseMock {
  if (kReleaseMode) {
    return const bool.fromEnvironment('USE_MOCK', defaultValue: false);
  }
  return const bool.fromEnvironment('USE_MOCK', defaultValue: true);
}

/// Backend API base URL.
/// Базовый URL бэкенда.
///
/// Override with: --dart-define=API_BASE_URL=https://api.example.com
/// Переопределить: --dart-define=API_BASE_URL=https://api.example.com
String get kApiBaseUrl {
  const fromEnv = String.fromEnvironment('API_BASE_URL');
  if (fromEnv.isNotEmpty) return fromEnv;
  return 'http://localhost:8080';
}

{{sentryDsn}}
''';


// di.dart — Dependency Injection setup / Настройка DI


const _tplDi = r'''
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

import 'di.config.dart';

/// Global GetIt instance for dependency injection.
/// Глобальный экземпляр GetIt для dependency injection.
final getIt = GetIt.instance;

/// Initializes all registered dependencies.
/// Инициализирует все зарегистрированные зависимости.
///
/// Call this in [main] before [runApp]. Pass the environment string
/// to select mock or prod implementations.
/// Вызовите в [main] перед [runApp]. Передайте строку окружения
/// для выбора mock или prod реализаций.
@InjectableInit()
Future<void> configureDependencies({String? environment}) =>
    getIt.init(environment: environment);
''';


// network_module.dart — Dio setup / Настройка Dio


const _tplNetworkModule = r'''
import 'package:dio/dio.dart';
import 'package:injectable/injectable.dart';
import 'package:nexo/nexo.dart';

import '../../config.dart';
import '../../network/auth_interceptor_bindings.dart';

/// Named identifier for the auth-only Dio instance.
/// Именованный идентификатор для Dio-экземпляра только для авторизации.
const authDioName = 'auth';

/// DI module providing Dio instances and interceptors.
/// DI-модуль, предоставляющий Dio-экземпляры и интерсепторы.
///
/// Two Dio instances:
/// Два Dio-экземпляра:
/// - [authDio] — for login/register/refresh (no auth interceptor to avoid
///               circular dependency).
///   Для login/register/refresh (без auth интерсептора во избежание
///   циклической зависимости).
/// - [dio] — for all authenticated API calls (with NexoAuthInterceptor).
///   Для всех авторизованных API-вызовов (с NexoAuthInterceptor).
@module
abstract class NetworkModule {
  BaseOptions get _baseOptions => BaseOptions(
        baseUrl: kApiBaseUrl.endsWith('/') ? kApiBaseUrl : '$kApiBaseUrl/',
        connectTimeout: const Duration(seconds: 15),
        receiveTimeout: const Duration(seconds: 30),
        headers: const {
          'Accept': 'application/json',
        },
      );

  /// Auth Dio — no token interceptor (used for login/register/refresh).
  /// Auth Dio — без интерсептора токена (для login/register/refresh).
  @Named(authDioName)
  @lazySingleton
  Dio authDio(NexoLogger logger) {
    final dio = Dio(_baseOptions);
    dio.interceptors.addAll([
      NexoRequestIdInterceptor(logger: logger),
      NexoLoggingInterceptor(logger: logger),
    ]);
    return dio;
  }

  /// Typed wrapper around auth Dio.
  /// Типизированная обёртка над auth Dio.
  @Named(authDioName)
  @lazySingleton
  DioClient authDioClient(@Named(authDioName) Dio dio) => DioClient(dio);

  /// Main Dio — with auth interceptor for token injection + refresh.
  /// Основной Dio — с auth интерсептором для инъекции токена + обновления.
  @lazySingleton
  Dio dio(NexoLogger logger, AuthInterceptorBindings auth) {
    final dio = Dio(_baseOptions);
    dio.interceptors.addAll([
      NexoRequestIdInterceptor(logger: logger),
      NexoLoggingInterceptor(logger: logger),
      NexoAuthInterceptor(
        dio: dio,
        getToken: auth.getAccessToken,
        refreshToken: auth.refreshAccessToken,
        onTokenExpired: auth.onTokenExpired,
      ),
    ]);
    return dio;
  }

  /// Typed wrapper around main Dio.
  /// Типизированная обёртка над основным Dio.
  @lazySingleton
  DioClient dioClient(Dio dio) => DioClient(dio);
}
''';


// storage_module.dart — Local storage / Локальное хранилище


const _tplStorageModule = r'''
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:injectable/injectable.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// DI module providing local storage instances.
/// DI-модуль, предоставляющий локальные хранилища.
///
/// - [SharedPreferences] — for simple key-value storage (settings, flags).
///   Для простого key-value хранения (настройки, флаги).
/// - [FlutterSecureStorage] — for sensitive data (tokens, keys).
///   Для чувствительных данных (токены, ключи).
@module
abstract class StorageModule {
  /// SharedPreferences — initialized before app starts (@preResolve).
  /// SharedPreferences — инициализируется до запуска приложения (@preResolve).
  @preResolve
  Future<SharedPreferences> get sharedPreferences =>
      SharedPreferences.getInstance();

  /// Secure storage for tokens and sensitive data.
  /// Безопасное хранилище для токенов и чувствительных данных.
  @lazySingleton
  FlutterSecureStorage get secureStorage => const FlutterSecureStorage();
}
''';


// logger_module.dart — Logging & crash reporting / Логирование и краш-репорты


const _tplLoggerModule = r'''
import 'package:injectable/injectable.dart';
import 'package:nexo/nexo.dart';
import 'package:talker/talker.dart';

/// DI module providing logging and crash reporting.
/// DI-модуль, предоставляющий логирование и краш-репорты.
///
/// Chain: Talker -> TalkerLoggerAdapter -> NexoLogger
/// Цепочка: Talker -> TalkerLoggerAdapter -> NexoLogger
@module
abstract class LoggerModule {
  /// Talker instance — underlying logger from the talker package.
  /// Экземпляр Talker — базовый логгер из пакета talker.
  @lazySingleton
  Talker get talker => Talker();

  /// Adapter bridging Talker to nexo's NexoLogger interface.
  /// Адаптер, связывающий Talker с интерфейсом NexoLogger.
  @lazySingleton
  TalkerLoggerAdapter talkerLoggerAdapter(Talker talker) =>
      TalkerLoggerAdapter(talker);

  /// NexoLogger instance — used throughout the app for structured logging.
  /// Экземпляр NexoLogger — используется во всём приложении для структурированного логирования.
  @lazySingleton
  NexoLogger nexoLogger(TalkerLoggerAdapter adapter) => adapter;

  /// Crash reporter — replace with Sentry/Crashlytics implementation.
  /// Краш-репортер — замените на реализацию Sentry/Crashlytics.
  @lazySingleton
  NexoCrashReporter nexoCrashReporter() => const NoOpNexoCrashReporter();
}
''';


// auth_interceptor_bindings.dart — Auth bridge / Мост авторизации


const _tplAuthBindings = r'''
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:injectable/injectable.dart';

/// Bridge between secure storage and [NexoAuthInterceptor].
/// Мост между безопасным хранилищем и [NexoAuthInterceptor].
///
/// Provides token read/write/refresh callbacks to the auth interceptor.
/// Предоставляет колбэки чтения/записи/обновления токенов для auth интерсептора.
///
/// IMPORTANT: Implement [refreshAccessToken] with your actual refresh endpoint.
/// ВАЖНО: Реализуйте [refreshAccessToken] с вашим реальным эндпоинтом обновления.
@lazySingleton
class AuthInterceptorBindings {
  AuthInterceptorBindings(this._secureStorage);

  final FlutterSecureStorage _secureStorage;

  static const _accessTokenKey = 'access_token';
  static const _refreshTokenKey = 'refresh_token';

  /// Reads the current access token from secure storage.
  /// Читает текущий access token из безопасного хранилища.
  Future<String?> getAccessToken() async {
    return _secureStorage.read(key: _accessTokenKey);
  }

  /// Refreshes the access token using the stored refresh token.
  /// Обновляет access token используя сохранённый refresh token.
  ///
  /// TODO: Replace with your actual refresh logic.
  /// TODO: Замените на вашу реальную логику обновления.
  Future<String> refreshAccessToken() async {
    final refreshToken = await _secureStorage.read(key: _refreshTokenKey);
    if (refreshToken == null) throw Exception('No refresh token');

    // TODO(nexo): implement token refresh via your auth API.
    // TODO(nexo): реализуйте обновление токена через ваш auth API.
    // final response = await dio.post('/auth/refresh', data: {'refresh_token': refreshToken});
    // final newAccessToken = response.data['access_token'] as String;
    // await _secureStorage.write(key: _accessTokenKey, value: newAccessToken);
    // return newAccessToken;

    throw UnimplementedError(
      'Implement refreshAccessToken: call your refresh endpoint, '
      'save new tokens, and return the new access token.',
    );
  }

  /// Called when the access token expires and cannot be refreshed.
  /// Вызывается когда access token истёк и не может быть обновлён.
  Future<void> onTokenExpired() async {
    await _secureStorage.delete(key: _accessTokenKey);
    await _secureStorage.delete(key: _refreshTokenKey);
    // TODO(nexo): navigate to login screen.
    // TODO(nexo): перейти на экран входа.
  }

  /// Saves tokens after successful login/registration.
  /// Сохраняет токены после успешного входа/регистрации.
  Future<void> saveTokens({
    required String accessToken,
    required String refreshToken,
  }) async {
    await _secureStorage.write(key: _accessTokenKey, value: accessToken);
    await _secureStorage.write(key: _refreshTokenKey, value: refreshToken);
  }

  /// Clears all tokens (on logout).
  /// Очищает все токены (при выходе).
  Future<void> clearTokens() async {
    await _secureStorage.delete(key: _accessTokenKey);
    await _secureStorage.delete(key: _refreshTokenKey);
  }
}
''';


// auto_route: app_router.dart — Router config / Конфигурация роутера


const _tplAutoRouteRouter = r'''
import 'package:auto_route/auto_route.dart';
import 'package:injectable/injectable.dart';

import '../navigation/auth_guard.dart';
import '../navigation/guest_guard.dart';

part 'app_router.gr.dart';

/// Application router using auto_route.
/// Роутер приложения на auto_route.
///
/// Routes are generated by `build_runner` into `app_router.gr.dart`.
/// Add [@RoutePage()] annotation to your page widgets, then register
/// them in [routes].
///
/// Роуты генерируются `build_runner` в `app_router.gr.dart`.
/// Добавьте аннотацию [@RoutePage()] к виджетам страниц,
/// затем зарегистрируйте их в [routes].
@AutoRouterConfig(replaceInRouteName: 'Page,Route')
@singleton
class AppRouter extends RootStackRouter {
  AppRouter(this._authGuard, this._guestGuard);

  final AuthGuard _authGuard;
  final GuestGuard _guestGuard;

  @override
  List<AutoRoute> get routes => [
        // TODO(nexo): add @RoutePage() annotation to your pages,
        // then add routes here.
        // TODO(nexo): добавьте аннотацию @RoutePage() к вашим страницам,
        // затем добавьте роуты сюда.
        //
        // Example / Пример:
        // AutoRoute(page: HomeRoute.page, initial: true),
        // AutoRoute(page: ProfileRoute.page, guards: [_authGuard]),
      ];
}
''';


// auto_route: auth_guard.dart — Auth guard / Гард авторизации


const _tplAuthGuard = r'''
import 'package:auto_route/auto_route.dart';
import 'package:injectable/injectable.dart';

/// Guard that requires the user to be authenticated.
/// Гард, требующий авторизации пользователя.
///
/// Redirects unauthenticated users to the login page.
/// Перенаправляет неавторизованных пользователей на страницу входа.
@singleton
class AuthGuard extends AutoRouteGuard {
  @override
  void onNavigation(
    NavigationResolver resolver,
    StackRouter router,
  ) {
    // TODO(nexo): check if user is authenticated.
    // TODO(nexo): проверьте, авторизован ли пользователь.
    //
    // final session = getIt<SessionCubit>().state;
    // if (session.isAuthenticated) {
    //   resolver.next(true);
    // } else {
    //   resolver.redirect(const LoginRoute());
    // }

    // Default: allow all navigations (remove when auth is implemented).
    // По умолчанию: разрешает все навигации (удалите после реализации auth).
    resolver.next(true);
  }
}
''';


// auto_route: guest_guard.dart — Guest guard / Гард для гостей


const _tplGuestGuard = r'''
import 'package:auto_route/auto_route.dart';
import 'package:injectable/injectable.dart';

/// Guard that requires the user to NOT be authenticated (guest only).
/// Гард, требующий, чтобы пользователь НЕ был авторизован (только для гостей).
///
/// Redirects authenticated users to the home page.
/// Перенаправляет авторизованных пользователей на главную страницу.
@singleton
class GuestGuard extends AutoRouteGuard {
  @override
  void onNavigation(
    NavigationResolver resolver,
    StackRouter router,
  ) {
    // TODO(nexo): check if user is NOT authenticated (guest only).
    // TODO(nexo): проверьте, что пользователь НЕ авторизован (только для гостей).
    //
    // final session = getIt<SessionCubit>().state;
    // if (!session.isAuthenticated) {
    //   resolver.next(true);
    // } else {
    //   resolver.redirect(const HomeRoute());
    // }

    // Default: allow all navigations (remove when auth is implemented).
    // По умолчанию: разрешает все навигации (удалите после реализации auth).
    resolver.next(true);
  }
}
''';


// go_router: app_router.dart — GoRouter config / Конфигурация GoRouter


const _tplGoRouter = r'''
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

/// Application router using go_router.
/// Роутер приложения на go_router.
///
/// Define routes as [GoRoute] instances. Use [StatefulShellRoute]
/// for bottom navigation with multiple branches.
///
/// Определите роуты как экземпляры [GoRoute]. Используйте [StatefulShellRoute]
/// для нижней навигации с несколькими ветками.
final appRouter = GoRouter(
  initialLocation: '/',
  routes: [
    GoRoute(
      path: '/',
      builder: (context, state) => const Scaffold(
        body: Center(child: Text('Home')),
      ),
    ),
    // TODO(nexo): add your routes here.
    // TODO(nexo): добавьте ваши роуты сюда.
  ],
);
''';
