import 'name_utils.dart';

/// Simple `{{feature}}` / `{{Feature}}` / `{{featureSnake}}` substitution for
/// feature scaffold templates.
///
/// [relativePosixPath] is relative to `lib/features/<snake>/` or
/// `test/features/<snake>/`, using `/` as separator.
abstract final class TemplateRenderer {
  TemplateRenderer._();

  /// Renders Dart source for a planned feature file.
  static String render(String relativePosixPath, NameUtils names) {
    final norm = relativePosixPath.replaceAll(r'\', '/');
    final template = _pickTemplate(norm);
    return _substitute(template, names);
  }

  static String _pickTemplate(String norm) {
    if (norm.endsWith('_test.dart')) {
      return _tplTest;
    }
    if (norm.endsWith('_entity.dart')) {
      return _tplEntity;
    }
    if (norm.endsWith('_page.dart')) {
      return _tplPage;
    }
    if (norm.endsWith('_widget.dart')) {
      return _tplWidget;
    }
    if (norm.endsWith('_local_datasource.dart')) {
      return _tplLocalDatasource;
    }
    if (norm.endsWith('_remote_datasource.dart')) {
      return _tplRemoteDatasource;
    }
    if (norm.contains('domain/repositories/') &&
        norm.endsWith('_repository.dart')) {
      return _tplRepository;
    }
    if (norm.contains('data/repositories/') &&
        norm.endsWith('_repository_impl.dart')) {
      return _tplRepositoryImpl;
    }
    if (norm.contains('domain/usecases/') &&
        norm.startsWith('domain/usecases/get_')) {
      return _tplUseCase;
    }
    if (norm.contains('presentation/bloc/') && norm.endsWith('_event.dart')) {
      return _tplBlocEvent;
    }
    if (norm.contains('presentation/bloc/') && norm.endsWith('_bloc.dart')) {
      return _tplBloc;
    }
    if (norm.contains('presentation/cubit/') && norm.endsWith('_cubit.dart')) {
      return _tplCubit;
    }
    if (norm.endsWith('_state.dart') &&
        (norm.contains('presentation/bloc/') ||
            norm.contains('presentation/cubit/'))) {
      return _tplState;
    }
    return _tplFallback;
  }

  static String _substitute(String template, NameUtils names) {
    return template
        .replaceAll('{{featureSnake}}', names.snakeCase)
        .replaceAll('{{Feature}}', names.pascalCase)
        .replaceAll('{{feature}}', _snakeToLowerCamel(names.snakeCase));
  }

  static String _snakeToLowerCamel(String snake) {
    final parts = snake.split('_').where((w) => w.isNotEmpty).toList();
    if (parts.isEmpty) {
      return snake;
    }
    return parts.first +
        parts
            .skip(1)
            .map((w) => '${w[0].toUpperCase()}${w.substring(1).toLowerCase()}')
            .join();
  }
}

const _tplFallback = r'''
// Placeholder generated by nexo_cli for {{featureSnake}}.
''';

const _tplEntity = r'''
class {{Feature}}Entity {
  const {{Feature}}Entity({required this.id});
  final String id;
}
''';

const _tplRepository = r'''
import 'package:nexo/nexo_errors.dart';

import '../entities/{{featureSnake}}_entity.dart';

abstract interface class {{Feature}}Repository {
  Future<Result<{{Feature}}Entity>> get{{Feature}}();
}
''';

const _tplRepositoryImpl = r'''
import 'package:nexo/nexo_core.dart';
import 'package:nexo/nexo_errors.dart';

import '../../domain/entities/{{featureSnake}}_entity.dart';
import '../../domain/repositories/{{featureSnake}}_repository.dart';
import '../datasources/{{featureSnake}}_remote_datasource.dart';

class {{Feature}}RepositoryImpl implements {{Feature}}Repository {
  {{Feature}}RepositoryImpl({required {{Feature}}RemoteDataSource remote})
      : _remote = remote;

  final {{Feature}}RemoteDataSource _remote;

  @override
  Future<Result<{{Feature}}Entity>> get{{Feature}}() async {
    try {
      final model = await _remote.fetch{{Feature}}();
      return Right(_mapModelToEntity(model));
    } catch (e, s) {
      return Left(e.toFailure(s));
    }
  }

  {{Feature}}Entity _mapModelToEntity({{Feature}}Model model) {
    // TODO(nexo): extend mapping when {{Feature}}Model gains fields beyond id.
    return {{Feature}}Entity(id: model.id);
  }
}
''';

const _tplUseCase = r'''
import 'package:nexo/nexo_core.dart';
import 'package:nexo/nexo_errors.dart';
import 'package:nexo/nexo_logger.dart';

import '../entities/{{featureSnake}}_entity.dart';
import '../repositories/{{featureSnake}}_repository.dart';

class Get{{Feature}}UseCase extends NexoUseCase<{{Feature}}Entity, NoParams> {
  Get{{Feature}}UseCase({
    required NexoLogger logger,
    required {{Feature}}Repository repository,
  })  : _repository = repository,
        super(logger);

  final {{Feature}}Repository _repository;

  @override
  Future<{{Feature}}Entity> execute(NoParams params) async {
    final result = await _repository.get{{Feature}}();
    return result.fold((failure) => throw failure, (entity) => entity);
  }
}
''';

const _tplRemoteDatasource = r'''
import 'package:nexo/nexo_core.dart';
import 'package:nexo/nexo_logger.dart';

class {{Feature}}Model {
  const {{Feature}}Model({required this.id});
  final String id;

  factory {{Feature}}Model.fromJson(Map<String, dynamic> json) {
    return {{Feature}}Model(id: json['id'] as String? ?? '');
  }

  Map<String, dynamic> toJson() => <String, dynamic>{'id': id};
}

class {{Feature}}RemoteDataSource extends BaseRemoteDataSource {
  {{Feature}}RemoteDataSource(super.client, {required super.logger});

  // TODO(nexo): implement network call when the endpoint is available.
  Future<{{Feature}}Model> fetch{{Feature}}() async {
    throw UnimplementedError('{{Feature}}RemoteDataSource.fetch{{Feature}}');
  }
}
''';

const _tplLocalDatasource = r'''
class {{Feature}}LocalDataSource {
  const {{Feature}}LocalDataSource();
}
''';

const _tplState = r'''
import 'package:nexo/nexo_core.dart';
import 'package:nexo/nexo_errors.dart';

import '../../domain/entities/{{featureSnake}}_entity.dart';

typedef {{Feature}}State = NexoAsyncState<{{Feature}}Entity>;
''';

const _tplBlocEvent = r'''
sealed class {{Feature}}Event {}

final class Load{{Feature}} extends {{Feature}}Event {}
''';

const _tplBloc = r'''
import 'package:nexo/nexo_core.dart';
import 'package:nexo/nexo_errors.dart';
import 'package:nexo/nexo_logger.dart';

import '../../domain/usecases/get_{{featureSnake}}_usecase.dart';
import '{{featureSnake}}_event.dart';
import '{{featureSnake}}_state.dart';

class {{Feature}}Bloc extends NexoBloc<{{Feature}}Event, {{Feature}}State> {
  {{Feature}}Bloc({
    required Get{{Feature}}UseCase get{{Feature}}UseCase,
    required NexoLogger logger,
  })  : _get{{Feature}}UseCase = get{{Feature}}UseCase,
        _logger = logger,
        super(const NexoAsyncIdle<{{Feature}}Entity>()) {
    on<Load{{Feature}}>(_onLoad);
    _logger.debug('{{Feature}}Bloc ready');
  }

  final Get{{Feature}}UseCase _get{{Feature}}UseCase;
  final NexoLogger _logger;

  Future<void> _onLoad(
    Load{{Feature}} event,
    Emitter<{{Feature}}State> emit,
  ) async {
    await executeEither<{{Feature}}Entity>(
      emit: emit,
      action: () => _get{{Feature}}UseCase(const NoParams()),
      onLoading: () => const NexoAsyncLoading<{{Feature}}Entity>(),
      onSuccess: (data) => NexoAsyncSuccess<{{Feature}}Entity>(data),
      onError: (failure) => NexoAsyncFailure<{{Feature}}Entity>(failure),
    );
  }
}
''';

const _tplCubit = r'''
import 'package:nexo/nexo_core.dart';
import 'package:nexo/nexo_errors.dart';
import 'package:nexo/nexo_logger.dart';

import '../../domain/usecases/get_{{featureSnake}}_usecase.dart';
import '{{featureSnake}}_state.dart';

class {{Feature}}Cubit extends NexoCubit<{{Feature}}State> {
  {{Feature}}Cubit({
    required Get{{Feature}}UseCase get{{Feature}}UseCase,
    required NexoLogger logger,
  })  : _get{{Feature}}UseCase = get{{Feature}}UseCase,
        _logger = logger,
        super(const NexoAsyncIdle<{{Feature}}Entity>()) {
    _logger.debug('{{Feature}}Cubit ready');
  }

  final Get{{Feature}}UseCase _get{{Feature}}UseCase;
  final NexoLogger _logger;

  Future<void> load() async {
    await executeEither<{{Feature}}Entity>(
      action: () => _get{{Feature}}UseCase(const NoParams()),
      onLoading: () => const NexoAsyncLoading<{{Feature}}Entity>(),
      onSuccess: (data) => NexoAsyncSuccess<{{Feature}}Entity>(data),
      onError: (failure) => NexoAsyncFailure<{{Feature}}Entity>(failure),
    );
  }
}
''';

const _tplPage = r'''
import 'package:flutter/material.dart';

class {{Feature}}Page extends StatelessWidget {
  const {{Feature}}Page({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(body: SizedBox.shrink());
  }
}
''';

const _tplWidget = r'''
import 'package:flutter/material.dart';

class {{Feature}}Widget extends StatelessWidget {
  const {{Feature}}Widget({super.key});

  @override
  Widget build(BuildContext context) {
    return const SizedBox.shrink();
  }
}
''';

const _tplTest = r'''
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('{{featureSnake}} smoke', () {
    expect(true, isTrue);
  });
}
''';
